name: C++ CMake Conan Clang-Tidy

on:
  workflow_call:

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: tnt-coders/ci-workflows/.github/actions/cpp-cmake-conan-setup@master
        with:
          preset: release

      - name: Install clang-tidy
        run: sudo apt-get install -y clang-tidy

      - name: Run clang-tidy
        run: run-clang-tidy -p build/release -warnings-as-errors='*'