name: C++ CMake Conan Lint

on:
  workflow_call:

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Setup
        uses: tnt-coders/ci-workflows/.github/actions/cpp-cmake-conan-setup@master

      - name: Install clang-tidy (Linux)
        if: runner.os == 'Linux'
        shell: bash
        run: sudo apt-get install -y clang-tidy

      - name: Install clang-tidy (macOS)
        if: runner.os == 'macOS'
        shell: bash
        run: |
          brew install llvm
          LLVM_PREFIX="$(brew --prefix llvm)"
          echo "$LLVM_PREFIX/bin" >> "$GITHUB_PATH"

      - name: Configure
        run: cmake --preset release

      - name: Lint
        run: cmake --build --preset release --target clang-tidy